### ISSUE TITLE
[Question] Validation of the JWT Token Expiry Time

### ISSUE THREAD

**Issue by sherifkayad** [Robbilie/nginx-jwt-auth#1]
First of all thanks for this useful project. Just wanted to ask if it's possible to validate on the `exp` (expiry time) of the passed token. Is that something you currently support? .. Would that be planned to be supported at some point of time?

My use case: some of our frontends may pass an expired token to the backends, that's when we want to know, throw an error and the frontend should be asking for a refresh and sending a new token.

**Comment by Robbilie** [comment]
Since this is using an external library i dont implement the exp/iat validation myself but the lib i am using does so, have you checked? because it should throw errors on tokens that have iat/exp values that are "incorrect"

**Comment by sherifkayad** [comment]
I will check and let you know ;)

**Comment by sherifkayad** [comment]
@Robbilie confirmed! with an expired token I get a 401 .. Thanks a lot.
