### ISSUE TITLE
Build image for arm64

### ISSUE THREAD

**Issue by bdalpe** [Robbilie/nginx-jwt-auth#4]
One of my K8s clusters is ARM only. A multi-platform build would be ideal in the Github workflow: https://docs.docker.com/build/ci/github-actions/multi-platform/

**Comment by bdalpe** [comment]
Happy to create a PR

**Comment by Robbilie** [comment]
took a bit of trial and error but now im happy, feel free to try out the latest tag, should have arm64 now, if you need other arches let me know, i can also create a tag if you want to have a pinned version
